/* 1.) Retrieve the details of all apartments in a specific building, sorted by apartment type.
        Assuming BuildingID = 2 
*/
SELECT *
FROM Apartment
WHERE BuildingID = 2
ORDER BY ApartmentType;

/* 2.)  Find all available apartments (not booked during a given date range).
        Assumed date is not between ‘2024-11-15’ and ‘2024-12-12’
*/
SELECT a.*
FROM Apartment AS a
LEFT JOIN Booking AS b ON a.ApartmentID = b.ApartmentID
AND (b.StartTime <= '2024-11-15' AND b.EndTime >= '2024-12-12')
WHERE b.BookingID IS NULL
AND a.Availability = 1;

/* 3.) List the buildings with the highest number of booked apartments. */
SELECT b.BuildingID, COUNT(DISTINCT bo.ApartmentID) AS BookedCount
FROM Building AS b
JOIN Apartment AS a ON b.BuildingID = a.BuildingID
JOIN Booking AS bo ON a.ApartmentID = bo.ApartmentID
GROUP BY b.BuildingID
ORDER BY BookedCount DESC
LIMIT 1;

/* 4.) Retrieve the total revenue generated by each building from bookings (assume booking cost = $100 per day). */
SELECT b.BuildingID, SUM((TO_DAYS(bo.EndTime) - TO_DAYS(bo.StartTime)) * 100) AS TotalRevenue
FROM Building AS b
JOIN Apartment AS a ON b.BuildingID = a.BuildingID
JOIN Booking AS bo ON a.ApartmentID = bo.ApartmentID
WHERE bo.Status = 'Confirmed'
OR bo.Status = 'Completed'
GROUP BY b.BuildingID;

/* 5.) Find guests who have made more than 2 bookings. */
SELECT g.Name AS Name, COUNT(b.GuestID) AS Bookings
FROM Guest AS g, Booking AS b
WHERE g.GuestID = b.GuestID
GROUP BY Name
HAVING Bookings > 2;

/* 6.) List all bookings that are currently active (ongoing based on the current date) */
SELECT *
FROM Booking
WHERE Status = 'Confirmed' 
AND StartTime >= CURDATE();


/* 7.)  Generate a report showing booking details (apartment, guest name, booking status) for a specific date range.
        Assuming date range is between ‘2024-11-18’ and ‘2024-12-18’
*/
SELECT a.ApartmentType AS  "Apartment", g.Name AS "Guest Name", b.status AS "Booking Status"
FROM Booking AS b
JOIN Guest AS g ON b.GuestID = g.GuestID
JOIN Apartment AS a ON b.ApartmentID = a.ApartmentID
WHERE b.StartTime >= '2024-11-18' AND b.EndTime <= '2024-12-18';